### ISSUE TITLE
Is there a reason the bento/ubuntu-14.04 box is used?

### ISSUE THREAD

**Issue by jonte** [erikboto/gdp-qtas-sde#1]
The Hashicorp box server seems to prioritize high-traffic images, and the current image doesn't seem very popular.. This seems to cause the current box to take a long while to download, while high-traffic ones, like the official Ubuntu boxes download pretty fast.

Is there a reason we're using the bento box? I am about to base a different Vagrantfile off this one, so I'd be interested in knowing any potential issues with the official boxes, id you've found any!

Thanks,

**Comment by erikboto** [comment]
The reason at the time was that it was actually recommended, see e.g. https://github.com/mitchellh/vagrant/issues/7155#issuecomment-228568200. That reason might not be valid anymore though.

If I recall correctly I think @andreasrosenlind did experiment with using official boxes instead.

**Comment by jonte** [comment]
Hmm.. That's good info. I noticed that the default user is "ubuntu" and not "vagrant", so there may be more oddities.. I'll keep this in mind if things break! Thanks!
